### PR TITLE
Refactoring and fixes

### LINKED ISSUE #79: Remove loop partition dialogue
Based on discussion #77 
Please remove this confusing dialogue from iotit
```
[+] Uploading 2017-04-10-raspbian-jessie-lite.img to virtual machine
   [1] loop0p1
   [2] loop0p2
[?] Please select the correct mounting point:
```

We should confirm ourselves in the background which to mount.

### PR DESCRIPTION
**Pull request by tectiv3**
Refactored vbox presets a bit.
Moved device workflow.go code inside device.go.
Fixed #79 
Altered text and formatting across the app.

### CODE REVIEW

File: iotit.go [hunk 1]
```diff
@@ -45,7 +45,7 @@ GLOBAL OPTIONS:
 var Version string
 
 // Env string came from linker
-var Env string
+var Env string = "dev"
```
Comment (dbsparkle) [inline iotit.go]: __[golint]__
* [golint] should omit type string from declaration of var Env; it will be inferred from the right-hand side

File: device/device.go [hunk 2]
```diff
@@ -43,3 +60,109 @@ func Init(typeFlag string) {
 		return
 	}
 }
+
+// New triggers select repository methods and initializes a new flasher
+func New(device string) (Flasher, error) {
```
Comment (dbsparkle) [inline device/device.go:65]: __[gometalinter]__
* [gocyclo] cyclomatic complexity 18 of function New() is high (> 15)

File: device/device.go [hunk 3]
```diff
@@ -43,3 +60,109 @@ func Init(typeFlag string) {
...
+				g = append(g, s)
+			}
+		}
+
+		if len(g) != 0 {
+			device = g[dialogs.SelectOneDialog("Please select your custom board: ", g)]
+		}
+
+	}
+	r := &repo.DeviceMapping{}
```
Comment (dbsparkle) [inline device/device.go]: __[gometalinter]__
* [ineffassign] ineffectual assignment to r
